name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          mi-frontend/package-lock.json
          mi-backend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd mi-frontend
        npm install
        
    - name: Install backend dependencies
      run: |
        cd mi-backend
        npm install
        
    - name: Build frontend
      run: |
        cd mi-frontend
        npm run build
        
    - name: Run tests (if available)
      run: |
        cd mi-frontend
        npm run test --if-present
